
services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shara2010@
      MYSQL_DATABASE: LostAndFound_db
      MYSQL_USER: shaz
      MYSQL_PASSWORD: aris0007@
    ports:
      - "3307:3306"  # Host machine port 3307 → MySQL container port 3306
    networks:
      - lostandfound-network
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: lostandfound-app
    container_name: lostandfound-app
    restart: always
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    networks:
      - lostandfound-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/LostAndFound_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: shaz
      SPRING_DATASOURCE_PASSWORD: aris0007@

networks:
  lostandfound-network:

volumes:
  mysql_data:
